services:
  server:
    build:
      context: ../server
      dockerfile: ../infra/server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../server:/app
      - /app/node_modules
      - ./infra/sqlite:/app/data
